spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: liu6713122616.
    url: jdbc:mysql://localhost:3306/sky-take-out-review

sky:
  take:
    out:
      secretKey: pengzhiliu
      ttlTime: 86400000

AliyunOSS:
  bucket-name: liu-sunset-sky-take-out
  endPoint: https://oss-cn-beijing.aliyuncs.com
  region: cn-beijing